### ISSUE TITLE
Releases with numeric prefixes aren't picked up by `npm update`

### ISSUE THREAD

**Issue by jesterfraud** [crowbartools/firebot-custom-scripts-types#26]
Releases `5.53.2-2` through `5.53.2-6` aren't picked up with an npm update in the starter template repo. Are they stable releases? If not, it might be less confusing to mark them as "pre-releases" in GitHub releases.

**Comment by ebiggz** [comment]
They are stable releases. The versioning for this repo is a little awkward because the intention is to keep its version matched to the version of Firebot that the types are aligned with. The issue is when we need to publish a new release for this repo but the Firebot version hasn't changed. For these releases, we've been using the "prelease tags" which is technically not in compliance with semver spec and causes the npm weirdness / confusion.

We'll probably need to reconsider how we version this repo. 

Thanks for bringing this up and apologies for an answer that is a year and a half late!
